on: [push, pull_request]

name: KV Service Integration Tests Continuous Integration

defaults:
  run:
    shell: bash
    working-directory: ./kv-service-tests

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt install -y protobuf-compiler libprotobuf-dev
        
      - name: Run cargo check
        run: cargo check

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt install -y protobuf-compiler libprotobuf-dev

      - name: Run cargo test
        run: cargo test -- --test-threads=1 --ignored

  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install dependencies
        run: sudo apt install -y protobuf-compiler libprotobuf-dev

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings